---
layout:         page
title:          【Go】Go 错误处理
date:           2020-01-03
author:         翼
header-img: image/bg.jpg
catalog: true
tags:
---

首先第一句，来自Go官方的一句话：[Errors are values](https://blog.golang.org/errors-are-values)。

Go内置的error是interface类型：
```go
type error interface {
    Error() string
}
```

Go标准包中给了两种创建error变量的方式：
```go
// simple string-based error
err1 := errors.New("math: square root of negative number")

// with formatting
err2 := fmt.Errorf("math: square root of negative number %g", x)
```

实际项目里面，仅仅是只用上面两种方式返回错误，是不够的。以我目前负责项目来看，会使用到两种错误处理方式：
1. 不需要特别处理的错误，比如只是需要记录日志。例如节目更新时会有一种情况是发现节目已经下线，这种情况下，上层代码不需要做什么错误处理。这个时候我只是简单地通过errors.New("...")返回一个错误。上层代码对这种错误会直接输出日志，并不需要做什么处理。
1. 需要特别处理的错误。例如更新节目时，发现第三方接口请求失败、数据库写入失败等等，上层代码需要考虑是否重试，或者把节目ID再重设到待更新队列里面去。这种情况下，我使用自定义的错误类型、以及 github.com/pkg/errors 包来包装底层错误。

#### 自定义错误
对于节目更新这里，上层需要知道错误的节目ID（节目ID更新是批量的）、错误类型信息等等。那么就有了如下的错误类型定义：
```go
type EntityOpError struct {
	Id int64
	ErrorCode int
}

func NewEntityOpError(id int64, code int) *EntityOpError {
	return &EntityOpError{
		Id: id,
		ErrorCode: code,
	}
}

func (err *EntityOpError) Error() string {
	return fmt.Sprintf("entity ops error:%s:%d", EntityErrorMap[err.ErrorCode], err.Id)
}

```
另外，为了方便输出日志以及规范这里可能出现的ErrorCode，还有一个单独的定义错误码的地方，如：
```go
package errdef

const ENTITY_WRITE_MGO_FAILED = 1
const ENTITY_READ_XXX_FAILED = 2
const ENTITY_TYPE_UNKNOWN = 3

var EntityErrorMap = map[int]string {
	ENTITY_WRITE_MGO_FAILED: "ENTITY_WRITE_MGO_FAILED",
	ENTITY_READ_XXX_FAILED: "ENTITY_READ_XXX_FAILED",
	ENTITY_TYPE_UNKNOWN: "ENTITY_TYPE_UNKNOWN",
}

```
上面定义了可能出现的错误码，以及为了方便在日志里面输出的可读的错误原因。

#### 包装错误 "github.com/pkg/errors"
代码里面经常有这种情况：A方法调用了B方法，B方法再调用了C方法。调用C时出现了错误，B获得了这个错误，但是B本身并不处理错误，可能只是需要将错误返回给上层业务代码来处理。

这种情况下，B方法该怎么办？最简单的当然是原封不动地返回C方法返回的错误。但是这不够好，因为会丢失B的上下文信息。更好一点的方式是，将C返回的错误返回给A时，一并附上B的上下文。
比如这里的这个方法，相当于C方法，它返回原始的错误，即自定义的错误类型EntityOpError：
```go
func getEntityType(entityId int64) (string, error) {
	end := entityId % 100
	if end == 0 {
		return "EPISODE", nil
	} else if end == 1 {
		return "ALBUM", nil
	} else {
		return "UNKNOWN", errdef.NewEntityOpError(entityId, errdef.ENTITY_TYPE_UNKNOWN)
	}
}

```

这里是B方法，它调用getEntityType获取entity的类型信息：
```go
// perrors "github.com/pkg/errors"

func getEntityInfo(entityId int64) (map[string]interface{}, error) {
	result := map[string]interface{}{}
	entityType, err := getEntityType(entityId)
	if err != nil {
		return result, perrors.Wrap(err, "get entity info")
	}

	result["type"] = entityType
	return result, nil
}

```

这里是A方法的部分代码，它调用getEntityInfo获取entity信息：
```go

info, err := getEntityInfo(entityId)

// 这里再调用Wrap就会出现调用栈重复的情况
// err = perrors.Wrap(err, "handle query entity")
// WithMessage只附加错误上下文，而不重复调用栈
err = perrors.WithMessage (err, "handle query entity" )

// 找到最底层的错误
if entityError, ok := perrors.Cause(err).(*errdef.EntityOpError); ok {
    fmt.Println("[ERROR] id:", entityError.Id, "context:", errdef.EntityErrorMap[entityError.ErrorCode])
    // 会输出包含Wrap过的错误, 如：handle query entity: get entity info: entity ops error:ENTITY_TYPE_UNKNOWN:123
    fmt.Println("format v:")
    fmt.Printf("%v\n", err)

    // 输出错误信息，以及调用栈
    fmt.Println("format +v:")
    fmt.Printf("%+v\n", err)
} else if err != nil {
    fmt.Printf("%v", err)
}
    
```
A里面，可以通过perrors.Cause(err)找到未被包装（Wrap、WithMessage）过的原始错误值。我们可以来判断它的类型并进行相应处理。这也表示：我们可以在B里面返回B自己的错误，这不会影响A对C的错误处理。